/* eslint-disable */
export default{
    about:{
      "url-api":"https://dog.ceo/dog-api/documentation/random",
      "categories":[
        "spaniel",
        "australian-shepherd",
        "finnish-lapphund",
        "terrier",
        "doberman",
        "waterdog-spanish",
        "mountain-swiss",
        "labrador",
        "bullterrier",
        "chihuahua",
        "husky"
      ]
    },
    dogs:[
      {
          "id":"1",
          "image":"https://images.dog.ceo/breeds/spaniel-cocker/n02102318_11221.jpg",
          "breed":"spaniel"
        },
      {
          "id":"2",
          "image":"https://images.dog.ceo/breeds/australian-shepherd/pepper2.jpg",
          "breed":"australian-shepherd"
        },
      {
          "id":"3",
          "image":"https://images.dog.ceo/breeds/finnish-lapphund/mochilamvan.jpg",
          "breed":"finnish-lapphund"
        },
      {
          "id":"4",
          "image":"https://images.dog.ceo/breeds/terrier-silky/n02097658_2022.jpg",
          "breed":"terrier"
        },
      {
          "id":"5",
          "image":"https://images.dog.ceo/breeds/spaniel-cocker/n02102318_9254.jpg",
          "breed":"spaniel"
        },
      {
          "id":"6",
          "image":"https://images.dog.ceo/breeds/terrier-sealyham/n02095889_5547.jpg",
          "breed":"terrier"
        },
      {
          "id":"7",
          "image":"https://images.dog.ceo/breeds/doberman/n02107142_9621.jpg",
          "breed":"doberman"
        },
      {
          "id":"8",
          "image":"https://images.dog.ceo/breeds/australian-shepherd/leroy.jpg",
          "breed":"australian-shepherd"
        },
      {
          "id":"9",
          "image":"https://images.dog.ceo/breeds/spaniel-cocker/n02102318_12265.jpg",
          "breed":"spaniel"
        },
      {
          "id":"10",
          "image":"https://images.dog.ceo/breeds/terrier-australian/n02096294_8268.jpg",
          "breed":"terrier"
        },
      {
          "id":"11",
          "image":"https://images.dog.ceo/breeds/waterdog-spanish/20180723_185559.jpg",
          "breed":"waterdog-spanish"
        },
      {
          "id":"12",
          "image":"https://images.dog.ceo/breeds/mountain-swiss/n02107574_2352.jpg",
          "breed":"mountain-swiss"
        },
      {
          "id":"13",
          "image":"https://images.dog.ceo/breeds/terrier-border/n02093754_234.jpg",
          "breed":"terrier"
        },
      {
          "id":"14",
          "image":"https://images.dog.ceo/breeds/labrador/n02099712_4965.jpg",
          "breed":"labrador"
        },
      {
          "id":"15",
          "image":"https://images.dog.ceo/breeds/bullterrier-staffordshire/n02093256_11023.jpg",
          "breed":"bullterrier"
        },
      {
          "id":"16",
          "image":"https://images.dog.ceo/breeds/doberman/n02107142_5783.jpg",
          "breed":"doberman"
        },
      {
          "id":"17",
          "image":"https://images.dog.ceo/breeds/spaniel-brittany/n02101388_733.jpg",
          "breed":"spaniel"
        },
      {
          "id":"18",
          "image":"https://images.dog.ceo/breeds/chihuahua/n02085620_1492.jpg",
          "breed":"chihuahua"
        },
      {
          "id":"19",
          "image":"https://images.dog.ceo/breeds/chihuahua/n02085620_3877.jpg",
          "breed":"chihuahua"
        },
      {
          "id":"20",
          "image":"https://images.dog.ceo/breeds/husky/n02110185_13197.jpg",
          "breed":"husky"
        },
      {
          "id":"21",
          "image":"https://images.dog.ceo/breeds/labrador/n02099712_9374.jpg",
          "breed":"labrador"
        }
    ]
  }