name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches_ignore: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: npm run pretest
